#!/bin/sh

export LD_LIBRARY_PATH="${APPDIR}/usr/lib:${LD_LIBRARY_PATH}"
export PATH="${APPDIR}/usr/bin:${PATH}"
export XDG_DATA_DIRS="${APPDIR}/usr/share:${XDG_DATA_DIRS}"

export GSETTINGS_SCHEMA_DIR="${APPDIR}/usr/share/glib-2.0/schemas/:${GSETTINGS_SCHEMA_DIR}"

"${APPDIR}/usr/bin/com.github.tkashkin.gamehub" "$@"
